### PR TITLE
enh: Moved save button to the bottom of the form

### LINKED ISSUE #95: Move or Change Save button
**Is your feature request related to a problem? Please describe.**
I didn't see the the save button at the first sight, when I finally saw it, I thought it was a footer button, so I had to scroll to know that button was to save the information.

**Describe the solution you'd like**
I'd like the button to be changed as a static one or move up to be more visible for the user.
I think it's perfect for mobile devices but for web I think is better a button at the end of the form as usual.

**Additional context**
I was looking for the button in the red rectangle section as in many other forms.
Screen Shot 2022-05-23 at 3 45 38 PM

### PR DESCRIPTION
**Pull request by its-ayush-07**
# Description

Modified and moved the save button to the bottom of the form, where it is more visible.

## Motivation and Context

Fixes #95 

## How Has This Been Tested?

Tested locally

## Screenshots (if appropriate)

Screenshot (22)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] This PR isn't a duplicate of a previous one

### CODE REVIEW

**Comment by its-ayush-07** [comment]
@sudip-mondal-2002  please review, and kindly add the hacktoberfest label as I'm contributing under it. Thanks :)

**Comment by sudip-mondal-2002** [comment]
Don't move the save button, just keep the button and additionally add your changes. Also, the download button isn't there in your screenshot. Keep that as well.

**Comment by its-ayush-07** [comment]
Screenshot (23)

@sudip-mondal-2002 , made the corresponding changes.

**Comment by sudip-mondal-2002** [comment]
no don't change the save button style, keep as it was, and add your button separately, I mean there should be two save buttons

**Comment by its-ayush-07** [comment]
> no don't change the save button style, keep as it was, and add your button separately, I mean there should be two save buttons

Oh okay, got it. I'll make the changes

**Comment by its-ayush-07** [comment]
Screenshot (24)

@sudip-mondal-2002 , is this alright?

**Pull request merged**
