### PR TITLE
404 page

### PR DESCRIPTION
**Pull request by NabajitS**
# Description

Created a new page404 component inside `app/src/Pages/`
The route to this page was set up `app/src/app.js` using react-router-dom.
Additional - A Font was imported from google fonts

Fixes # (issue)
Created 404 page

## Motivation and Context
It's a 404 page
[Issue#65](https://github.com/Portfolio-Shop/portfolioshop/issues/65)

## How Has This Been Tested?
It, has been tested locally.

## Screenshots (if appropriate)
404page

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] This PR isn't a duplicate of a previous one

### CODE REVIEW

**Comment by NabajitS** [comment]
I have no idea as to why these checks are failing.
I just made changes to the UI
I'm quite new to open source, so could you please point it out

**Comment by sudip-mondal-2002** [comment]
@NabajitS don't worry about it.

**Comment by NabajitS** [comment]
Is there any problem with my PR ?
I would love to get some feedback

**Comment by sudip-mondal-2002** [comment]
I have requested some updates in your code, this is minor change, please do that. rest all very fine.

**Comment by NabajitS** [comment]
@sudip-mondal-2002  sorry but what do you mean?
Where do I look?

**Comment by sudip-mondal-2002** [comment]
image

**Comment by NabajitS** [comment]
Done, sorry about that.

**Pull request merged**
